In [1]:
import numpy as np
import pandas as pd

# Decision Tree 

## Problem 1

In [2]:
data = pd.read_csv('01_homework_dataset.csv')
data

x1   x2   x3   z
0   5.5  0.5  4.5   2
1   7.4  1.1  3.6   0
2   5.9  0.2  3.4   2
3   9.9  0.1  0.8   0
4   6.9 -0.1  0.6   2
5   6.8 -0.3  5.1   2
6   4.1  0.3  5.1   1
7   1.3 -0.2  1.8   1
8   4.5  0.4  2.0   0
9   0.5  0.0  2.3   1
10  5.9 -0.1  4.4   0
11  9.3 -0.2  3.2   0
12  1.0  0.1  2.8   1
13  0.4  0.1  4.3   1
14  2.7 -0.5  4.2   1

In [3]:
from DecisionTree import *
dt = DecisionTree(criterion='gini', 
                  max_depth=2, 
                  min_split_node=1, 
                  eps=1e-5, 
                  problem_type='classification')
X_train = data.iloc[:, [0, 1, 2]].values
y_train = data.iloc[:, 3].values

In [4]:
dt.fit(X_train, y_train)

In [5]:
dt.root_node

{'feature_value': 4.3,
 'feature_idx': 0,
 'is_categorical': False,
 'criterion_value': 0.6577777777777778,
 'split_cost': 0.49382716049382713,
 'distribution': [5, 6, 4],
 'left': {'feature_value': None,
  'feature_idx': None,
  'is_categorical': None,
  'criterion_value': 0.0,
  'split_cost': None,
  'distribution': [0, 6, 0],
  'left': None,
  'right': None},
 'right': {'feature_value': 4.45,
  'feature_idx': 2,
  'is_categorical': False,
  'criterion_value': 0.49382716049382713,
  'split_cost': 0.40816326530612246,
  'distribution': [5, 0, 4],
  'left': {'feature_value': None,
   'feature_idx': None,
   'is_categorical': None,
   'criterion_value': 0.40816326530612246,
   'split_cost': None,
   'distribution': [5, 0, 2],
   'left': None,
   'right': None},
  'right': {'feature_value': None,
   'feature_idx': None,
   'is_categorical': None,
   'criterion_value': 0.0,
   'split_cost': None,
   'distribution': [0, 0, 2],
   'left': None,
   'right': None}}}

In [6]:
dt.export_to_graphviz()

## Problem 2

In [7]:
X_pred = np.array([[4.1, -0.1, 2.2], 
                   [6.1, 0.4, 1.3]])

In [8]:
y_pred_proba_dt = dt.predict_proba(X_pred)
y_pred_proba_dt

array([[0.        , 1.        , 0.        ],
       [0.71428571, 0.        , 0.28571429]])

In [9]:
y_pred_dt = dt.predict(X_pred)
y_pred_dt

array([1, 0])

## Problem 4

In [10]:
from kNearestNeighbours import *

In [11]:
knn_classifier = kNearestNeighbours(X_train=X_train, 
                                    y_train=y_train, 
                                    k=3, 
                                    distance='euclidean', 
                                    weighted=False, 
                                    sigma=None, 
                                    problem_type='classification')

In [12]:
y_pred_proba_knn_classifier = knn_classifier.predict_proba(X_pred)
y_pred_proba_knn_classifier

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.        , 0.66666667]])

In [13]:
y_pred_knn_classifier = knn_classifier.predict(X_pred)
y_pred_knn_classifier

array([0, 2])

## Problem 5

In [14]:
knn_regressor = kNearestNeighbours(X_train=X_train, 
                                   y_train=y_train, 
                                   k=3, 
                                   distance='euclidean', 
                                   weighted=False, 
                                   sigma=None, 
                                   problem_type='regression')

In [15]:
y_pred_proba_knn_regressor = knn_regressor.predict(X_pred)
y_pred_proba_knn_regressor

array([1.        , 1.33333333])

## Problem 6